"2","Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  TypeError: cannot determine truth value of Relational
[90mRun ]8;;rstudio:run:reticulate::py_last_error()`reticulate::py_last_error()`]8;; for details.[39m
"
"0","quit"
"0","knitr::include_graphics(""./figs/Fig7.13.svg"")"
